config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match '/login', to: 'login#user_login', constraints: { subdomain: /.+/ }, via: [:get], as: 'login'
  match '/login', to: 'login#user_sign_in', constraints: { subdomain: /.+/ }, via: [:post], as: 'sign_in'
  match '/logout', to: 'login#user_sign_out', constraints: { subdomain: /.+/ }, via: [:delete], as: 'logout'
  
  match '/dashboard', to: 'dashboard#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/subjects/:id/announcements/', to: 'subject#announcements', constraints: { subdomain: /.+/ }, via: [:get], as: 'subject_announcements'
  match '/subjects/:id/documents/new', to: 'document#new', constraints: { subdomain: /.+/ }, via: [:get], as: 'new_documents'
  match '/subjects/:id/documents/', to: 'document#create', constraints: { subdomain: /.+/ }, via: [:post], as: 'documents'

  match '/subjects/:id/documents/:doc_id/download', to: 'document#download_file', constraints: { subdomain: /.+/ }, via: [:get], as: 'download_document'
  match '/subjects/:id/documents/:doc_id/download', to: 'document#delete_file', constraints: { subdomain: /.+/ }, via: [:delete], as: 'delete_document'
  match '/announcements', to: 'announcement#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/announcements/new', to: 'announcement#new', constraints: { subdomain: /.+/ }, via: [:get]
  match '/announcements/:id', to: 'announcement#show', constraints: { subdomain: /.+/ }, via: [:get], as: 'announcement'
  match '/announcements/', to: 'announcement#create', constraints: { subdomain: /.+/ }, via: [:post]
  match '/announcements/:id', to: 'announcement#destroy', constraints: { subdomain: /.+/ }, via: [:delete], as: 'delete_announcement'
  match '/subjects/', to: 'subject#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/subjects/:id', to: 'subject#show', constraints: { subdomain: /.+/ }, via: [:get], as: 'subject'


  get '/pricing/', to: 'front#pricing'
  get '/users/register', to: 'login#admin_register', as: 'user_register'
  post '/users/register', to: 'login#admin_create'
  resources :admin_user, path: 'admin/admin_user'
  resources :admin_teacher, path: 'admin/admin_teacher'
  resources :admin_student, path: 'admin/admin_student'
  resources :admin_subject, path: 'admin/admin_subject'
  resources :admin_announcement, path: 'admin/admin_announcement'
  get 'admin/profile', to: 'admin_profile#show', as: 'admin_profile'
  get 'admin/profile/edit', to: 'admin_profile#edit', as: 'admin_profile_edit'
  patch 'admin/profile/edit', to: 'admin_profile#update'
  root to: 'front#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :subject, optional: true
  belongs_to :company
end

app/controllers/announcement_controller.rb
class AnnouncementController < ApplicationController
    before_action :auth_user
    layout "backend_application"
    protect_from_forgery
    def index
        @announcements = Announcement.where(company_id: current_user.info.company_id).paginate(:page => params[:page], :per_page => 10)
        @dashboard_title = 'Announcement'
    end
    def show
        @announcement = Announcement.find(params[:id])
        @dashboard_title = 'Announcement'
    end
    def new
        @announcement = Announcement.new
        @subjects = current_user.teaches
        @dashboard_title = 'Announcement'
    end
    def create
        @announcement = Announcement.new(announcement_params)
        @announcement.subject = Subject.find(params[:subject][:subject_id])
        @announcement.company_id = current_user.info.company.id
        if @announcement.save
            @students = @announcement.subject.students
            @students.each do |s|
                UserMailer.announcement_email(s.email,@announcement.title,@announcement.content).deliver_now
            end
           
          flash[:notice] = 'Announcement created!'
          redirect_to dashboard_path
        else
            puts @announcement.errors.messages
          flash[:alert] = 'Failed to create announcement!'
          render :new
        end
    end
    def destroy
        @announcement = Announcement.find(params[:id])
        if @announcement.delete
            flash[:notice] = 'Announcement deleted!'
            redirect_to announcements_path
            
        else
            flash[:alert] = 'Failed to delete this announcement!'
            render :destroy
        end
    end
    private
    def announcement_params
        params.require(:announcement).permit(:title, :content, {:subject => [:subject_id]})
      end
end

app/helpers/announcement_helper.rb
module AnnouncementHelper
end

app/views/announcement/index.html.erb
<div class = "row">
        <div class="col-xs-12 col-md-8 col-md-push-2">
<div class="box box-success col-xs-12">
            <div class="box-header with-border">
              <h3 class="box-title">Announcements</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body col-xs-12">
              <ul class="products-list product-list-in-box">
                <% @announcements.each do |a|%>
  
                <li class="item col-xs-12">
                  <div class="product-info">
                      <%= link_to a.title, announcement_path(a), :class => 'product-title' %>
                    <br>
                    <h6 class="label label-default "><%= a.created_at.to_date %></h6>
                    <% if a.subject %>
                      <%= link_to a.subject.title, subject_path(a.subject), :class => 'label label-warning' %>
                    <% else %>
                      <h5 class = "label label-warning">All</h5>
                    <% end%>
                    
                  </div>
                </li>
                <% end %>

                <!-- /.item -->
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
                <%= will_paginate @announcements  %>
              <% if current_user.info.is_teacher %>
                <div class = "col-xs-12">
                  <%= link_to 'Create Announcement', announcements_new_path, :class => 'btn btn-sm btn-success btn-flat col-xs-12 col-md-4 col-md-push-4 view-more' %>
                </div>
              <% end %>
            </div>
            <!-- /.box-footer -->
          </div>
        
          <!-- /.box -->
        </div>

</div>

app/views/announcement/new.html.erb
<div class = "row">
            <div class="col-xs-12 col-md-8 col-md-push-2">
        <div class="box box-success col-xs-12">
                    <div class="box-header with-border">
                      <h3 class="box-title">Create Announcement</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body col-xs-12">
                      <ul class="products-list product-list-in-box">
                        <%= form_for @announcement, url: {action: "create"} do |f| %>
                            <div class="form-group">
                                <label for="announcement_title">Title:</label>
                                <%= f.text_field :title, :class => "form-control" %>
                            </div>
                            <div class="form-group">
                                <label for="announcement_content">Content:</label>
                                <%= f.text_area :content, :class => "form-control" %>
                            </div>
                            <div class="form-group">
                                <label for="announcement_subject">Subject:</label>
                                <%= select("subject", "subject_id", current_user.teaches.all.collect {|p| [ p.title, p.id ] }, { include_blank: false }, :class => 'form-control') %>
                            </div>
                            
                        <!-- /.item -->
                      </ul>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer text-center">
                       <% if current_user.info.is_teacher %>
                        <%= f.submit "Create",:class => 'btn btn-sm btn-success btn-flat col-xs-12 view-more' %>
                      <% end %>
                      <% end %>
                      
                    </div>
                    <!-- /.box-footer -->
                  </div>
                
                  <!-- /.box -->
                </div>
        </div>

app/views/announcement/show.html.erb
<div class = "row">
        <div class="col-xs-12 col-md-8 col-md-push-2">
<div class="box box-success col-xs-12">
            <div class="box-header with-border">
              <h3 class="box-title">Announcements</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body col-xs-12">
              <ul class="products-list product-list-in-box">

                <li class="item col-xs-12">
                  <div class="product-info">
                      <h6><%= @announcement.title %></h6>
                      <h6><%= @announcement.content %></h6>
                    <br>
                    <h6 class="label label-default "><%= @announcement.created_at.to_date %></h6>
                    
                  </div>
                </li>


                <!-- /.item -->
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
              <% if current_user.info.is_teacher && !@announcement.subject.nil? && @announcement.subject.user_id == current_user.id %>
                <div class = "col-xs-12">
                <%= link_to "Delete", delete_announcement_path(@announcement),  method: :delete, data: {confirm: "Are you sure you want to delete this announcement?"}, :class => 'btn btn-sm btn-danger btn-flat col-xs-12 col-md-4 col-md-push-4 view-more' %>
                </div>
              <% end %>
            </div>
            <!-- /.box-footer -->
          </div>
        
          <!-- /.box -->
        </div>

</div>