config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match '/login', to: 'login#user_login', constraints: { subdomain: /.+/ }, via: [:get], as: 'login'
  match '/login', to: 'login#user_sign_in', constraints: { subdomain: /.+/ }, via: [:post], as: 'sign_in'
  match '/logout', to: 'login#user_sign_out', constraints: { subdomain: /.+/ }, via: [:delete], as: 'logout'
  
  match '/dashboard', to: 'dashboard#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/subjects/:id/announcements/', to: 'subject#announcements', constraints: { subdomain: /.+/ }, via: [:get], as: 'subject_announcements'
  match '/subjects/:id/documents/new', to: 'document#new', constraints: { subdomain: /.+/ }, via: [:get], as: 'new_documents'
  match '/subjects/:id/documents/', to: 'document#create', constraints: { subdomain: /.+/ }, via: [:post], as: 'documents'

  match '/subjects/:id/documents/:doc_id/download', to: 'document#download_file', constraints: { subdomain: /.+/ }, via: [:get], as: 'download_document'
  match '/subjects/:id/documents/:doc_id/download', to: 'document#delete_file', constraints: { subdomain: /.+/ }, via: [:delete], as: 'delete_document'
  match '/announcements', to: 'announcement#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/announcements/new', to: 'announcement#new', constraints: { subdomain: /.+/ }, via: [:get]
  match '/announcements/:id', to: 'announcement#show', constraints: { subdomain: /.+/ }, via: [:get], as: 'announcement'
  match '/announcements/', to: 'announcement#create', constraints: { subdomain: /.+/ }, via: [:post]
  match '/announcements/:id', to: 'announcement#destroy', constraints: { subdomain: /.+/ }, via: [:delete], as: 'delete_announcement'
  match '/subjects/', to: 'subject#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/subjects/:id', to: 'subject#show', constraints: { subdomain: /.+/ }, via: [:get], as: 'subject'


  get '/pricing/', to: 'front#pricing'
  get '/users/register', to: 'login#admin_register', as: 'user_register'
  post '/users/register', to: 'login#admin_create'
  resources :admin_user, path: 'admin/admin_user'
  resources :admin_teacher, path: 'admin/admin_teacher'
  resources :admin_student, path: 'admin/admin_student'
  resources :admin_subject, path: 'admin/admin_subject'
  resources :admin_announcement, path: 'admin/admin_announcement'
  get 'admin/profile', to: 'admin_profile#show', as: 'admin_profile'
  get 'admin/profile/edit', to: 'admin_profile#edit', as: 'admin_profile_edit'
  patch 'admin/profile/edit', to: 'admin_profile#update'
  root to: 'front#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :auth_user
    layout "backend_application"
    def index
        @announcements = Announcement.where(company_id: current_user.info.company_id).last(5).reverse
        if current_user.info.is_teacher then
            @subjects = current_user.teaches
        else
            @subjects = current_user.subjects
        end
    
        @dashboard_title = 'Dashboard'
    end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class = "row">
        <div class="col-xs-12 col-md-8 col-md-push-2">
<div class="box box-success col-xs-12">
            <div class="box-header with-border">
              <h3 class="box-title">Announcements</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body col-xs-12">
              <ul class="products-list product-list-in-box">
                <% @announcements.each do |a|%>
  
                <li class="item col-xs-12">
                  <div class="product-info">
                      <%= link_to a.title, announcement_path(a), :class => 'product-title' %>
                    <br>
                    <h6 class="label label-default "><%= a.created_at.to_date %></h6>
                    <% if a.subject %>
                      <% if a.subject.teacher == current_user %>
                        <%= link_to a.subject.title, subject_path(a.subject), :class => 'label label-warning' %>
                      <% else %>
                        <h5 class = "label label-warning"><%= a.subject.title %></h5>
                      <% end%>
                    <% else %>
                    <h5 class = "label label-warning">All</h5>
                    <% end%>
                    
                    
                  </div>
                </li>
                <% end %>

                <!-- /.item -->
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
                <div class = "col-xs-12">
                  <% if current_user.info.is_teacher %>
                      <%= link_to 'View all', announcements_path, :class => 'btn btn-sm btn-info btn-flat col-xs-12 col-md-5 view-more' %>
                      <%= link_to 'Create Announcement', announcements_new_path, :class => 'btn btn-sm btn-success btn-flat col-xs-12 col-md-5 col-md-push-2 hidden-xs hidden-sm view-more' %>
                  <% else %> 
                  <%= link_to 'View all', announcements_path, :class => 'btn btn-sm btn-info btn-flat col-xs-12 col-md-6 col-md-push-3 view-more' %>
                  <% end %>
                </div>
              <% if current_user.info.is_teacher %>
                <div class = "col-xs-12">
                  <%= link_to 'Create Announcement', announcements_new_path, :class => 'btn btn-sm btn-success btn-flat col-xs-12 col-md-4 col-md-push-4 hidden-md hidden-lg view-more' %>
                </div>
              <% end %>
            </div>
            <!-- /.box-footer -->
          </div>
        
          <!-- /.box -->
        </div>

        <div class="col-xs-12 col-md-8 col-md-push-2">
            <div class="box box-success col-xs-12">
                        <div class="box-header with-border">
                          <h3 class="box-title">Subjects</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body col-xs-12">
                          <ul class="products-list product-list-in-box">
                            <% @subjects.each do |s|%>
              
                            <li class="item col-xs-12">
                              <div class="product-info">
                                  <%= link_to s.title, subject_path(s), :class => 'product-title' %>
                                <br>
                              </div>
                            </li>
                            <% end %>
            
                            <!-- /.item -->
                          </ul>
                        </div>
                      </div>
                    
                      <!-- /.box -->
                    </div>
</div>