config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match '/login', to: 'login#user_login', constraints: { subdomain: /.+/ }, via: [:get], as: 'login'
  match '/login', to: 'login#user_sign_in', constraints: { subdomain: /.+/ }, via: [:post], as: 'sign_in'
  match '/logout', to: 'login#user_sign_out', constraints: { subdomain: /.+/ }, via: [:delete], as: 'logout'
  
  match '/dashboard', to: 'dashboard#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/subjects/:id/announcements/', to: 'subject#announcements', constraints: { subdomain: /.+/ }, via: [:get], as: 'subject_announcements'
  match '/subjects/:id/documents/new', to: 'document#new', constraints: { subdomain: /.+/ }, via: [:get], as: 'new_documents'
  match '/subjects/:id/documents/', to: 'document#create', constraints: { subdomain: /.+/ }, via: [:post], as: 'documents'

  match '/subjects/:id/documents/:doc_id/download', to: 'document#download_file', constraints: { subdomain: /.+/ }, via: [:get], as: 'download_document'
  match '/subjects/:id/documents/:doc_id/download', to: 'document#delete_file', constraints: { subdomain: /.+/ }, via: [:delete], as: 'delete_document'
  match '/announcements', to: 'announcement#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/announcements/new', to: 'announcement#new', constraints: { subdomain: /.+/ }, via: [:get]
  match '/announcements/:id', to: 'announcement#show', constraints: { subdomain: /.+/ }, via: [:get], as: 'announcement'
  match '/announcements/', to: 'announcement#create', constraints: { subdomain: /.+/ }, via: [:post]
  match '/announcements/:id', to: 'announcement#destroy', constraints: { subdomain: /.+/ }, via: [:delete], as: 'delete_announcement'
  match '/subjects/', to: 'subject#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/subjects/:id', to: 'subject#show', constraints: { subdomain: /.+/ }, via: [:get], as: 'subject'


  get '/pricing/', to: 'front#pricing'
  get '/users/register', to: 'login#admin_register', as: 'user_register'
  post '/users/register', to: 'login#admin_create'
  resources :admin_user, path: 'admin/admin_user'
  resources :admin_teacher, path: 'admin/admin_teacher'
  resources :admin_student, path: 'admin/admin_student'
  resources :admin_subject, path: 'admin/admin_subject'
  resources :admin_announcement, path: 'admin/admin_announcement'
  get 'admin/profile', to: 'admin_profile#show', as: 'admin_profile'
  get 'admin/profile/edit', to: 'admin_profile#edit', as: 'admin_profile_edit'
  patch 'admin/profile/edit', to: 'admin_profile#update'
  root to: 'front#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :enrolls, dependent: :destroy
    has_many :documents, dependent: :destroy
    has_many :students, through: :enrolls, source: :user
    belongs_to :teacher, class_name: "User", foreign_key: "user_id"
    has_many :announcements, dependent: :destroy
    belongs_to :company

    def get_title_code()
        self[:title] + ' (' + self[:code] + ')'
    end   
end

app/controllers/subject_controller.rb
class SubjectController < ApplicationController
    before_action :auth_user
    layout "backend_application"
    protect_from_forgery
    def index
       if current_user.info.is_teacher then
        @subjects = current_user.teaches
       else
        @subjects = current_user.subjects
       end
       @dashboard_title = 'Subject'
    
    end
    def show
        @subject = Subject.find(params[:id])
        @dashboard_title = 'Subject'
        @announcements = Announcement.where(subject: @subject.id).last(5).reverse
    end
    def announcements
         @subject = Subject.find(params[:id])
         @dashboard_title = 'Subject'
         @announcements = Announcement.where(subject: @subject.id).paginate(:page => params[:page], :per_page => 10)
    end
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/views/subject/announcements.html.erb
<div class = "row">
  <div class = "col-xs-12 col-md-8 col-md-push-2 subject-title">
    <h3><%= @subject.title %></h3>
  </div>
    <div class="col-xs-12 col-md-8 col-md-push-2">
<div class="box box-success col-xs-12">
            <div class="box-header with-border">
              <h3 class="box-title">Announcements</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body col-xs-12">
              <ul class="products-list product-list-in-box">
                <% @announcements.each do |a|%>
  
                <li class="item col-xs-12">
                  <div class="product-info">
                      <%= link_to a.title, announcement_path(a), :class => 'product-title' %>
                    <br>
                    <h6 class="label label-default "><%= a.created_at.to_date %></h6>
                    <%= link_to a.subject.title, subject_path(a.subject), :class => 'label label-warning' %>
                    
                  </div>
                </li>
                <% end %>

                <!-- /.item -->
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
              <%= will_paginate @announcements  %>
            </div>
            <!-- /.box-footer -->
          </div>
        
          <!-- /.box -->
        </div>
</div>

app/views/subject/index.html.erb
<div class = "row">

        <div class="col-xs-12 col-md-8 col-md-push-2">
            <div class="box box-success col-xs-12">
                        <div class="box-header with-border">
                          <h3 class="box-title">Subjects</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body col-xs-12">
                          <ul class="products-list product-list-in-box">
                            <% @subjects.each do |s|%>
              
                            <li class="item col-xs-12">
                              <div class="product-info">
                                  <%= link_to s.title, subject_path(s), :class => 'product-title' %>
                                <br>
                              </div>
                            </li>
                            <% end %>
            
                            <!-- /.item -->
                          </ul>
                        </div>
                        <!-- /.box-body -->
                        <!-- /.box-footer -->
                      </div>
                    
                      <!-- /.box -->
                    </div>
</div>

app/views/subject/show.html.erb
<div class = "row">
  <div class = "col-xs-12 col-md-8 col-md-push-2 subject-title">
    <h3><%= @subject.title %></h3>
  </div>
    <div class="col-xs-12 col-md-8 col-md-push-2">
<div class="box box-success col-xs-12">
            <div class="box-header with-border">
              <h3 class="box-title">Announcements</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body col-xs-12">
              <ul class="products-list product-list-in-box">
                <% @announcements.each do |a|%>
  
                <li class="item col-xs-12">
                  <div class="product-info">
                      <%= link_to a.title, announcement_path(a), :class => 'product-title' %>
                    <br>
                    <h6 class="label label-default "><%= a.created_at.to_date %></h6>
                    <%= link_to a.subject.title, subject_path(a.subject), :class => 'label label-warning' %>
                    
                  </div>
                </li>
                <% end %>

                <!-- /.item -->
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
              <%= link_to 'View all', subject_announcements_path(@subject), :class => 'btn btn-sm btn-info btn-flat col-xs-12 view-more' %>
            </div>
            <!-- /.box-footer -->
          </div>
        
          <!-- /.box -->
        </div>
        <div class="col-xs-12 col-md-8 col-md-push-2">
            <div class="box box-success col-xs-12">
                        <div class="box-header with-border">
                          <h3 class="box-title">Documents</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body col-xs-12">
                          <ul class="products-list product-list-in-box">
                            <% @subject.documents.each do |s|%>
              
                            <li class="item col-xs-12">
                                    <div class="product-info">
                                         <%= link_to s.doc.file.filename, download_document_path(@subject.id,s.id), :class => 'product-title' %>
                                          <br>
                                          <h6 class="label label-default "><%= s.created_at.to_date %></h6>
                                          <% if current_user.info.is_teacher && @subject.user_id == current_user.id%>
                                            <%= link_to "Delete", delete_document_path(@subject.id,s.id),  method: :delete, data: {confirm: "Are you sure you want to delete this document?"}, :class => 'label label-danger' %>
                                          <% end %>
                                        </div>
                              <div class="product-info">
                                   
                                <br>
                              </div>
                            </li>
                            <% end %>
            
                            <!-- /.item -->
                          </ul>
                        </div>
                        <!-- /.box-body -->
                        <% if current_user.info.is_teacher %>
                        <div class="box-footer text-center">
                          <%= link_to 'Upload Document', new_documents_path(@subject), :class => 'btn btn-sm btn-success btn-flat col-xs-12 view-more' %>
                        </div>
                        <% end %>
                        <!-- /.box-footer -->
                      </div>
                    
                      <!-- /.box -->
                    </div>
</div>