config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match '/login', to: 'login#user_login', constraints: { subdomain: /.+/ }, via: [:get], as: 'login'
  match '/login', to: 'login#user_sign_in', constraints: { subdomain: /.+/ }, via: [:post], as: 'sign_in'
  match '/logout', to: 'login#user_sign_out', constraints: { subdomain: /.+/ }, via: [:delete], as: 'logout'
  
  match '/dashboard', to: 'dashboard#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/subjects/:id/announcements/', to: 'subject#announcements', constraints: { subdomain: /.+/ }, via: [:get], as: 'subject_announcements'
  match '/subjects/:id/documents/new', to: 'document#new', constraints: { subdomain: /.+/ }, via: [:get], as: 'new_documents'
  match '/subjects/:id/documents/', to: 'document#create', constraints: { subdomain: /.+/ }, via: [:post], as: 'documents'

  match '/subjects/:id/documents/:doc_id/download', to: 'document#download_file', constraints: { subdomain: /.+/ }, via: [:get], as: 'download_document'
  match '/subjects/:id/documents/:doc_id/download', to: 'document#delete_file', constraints: { subdomain: /.+/ }, via: [:delete], as: 'delete_document'
  match '/announcements', to: 'announcement#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/announcements/new', to: 'announcement#new', constraints: { subdomain: /.+/ }, via: [:get]
  match '/announcements/:id', to: 'announcement#show', constraints: { subdomain: /.+/ }, via: [:get], as: 'announcement'
  match '/announcements/', to: 'announcement#create', constraints: { subdomain: /.+/ }, via: [:post]
  match '/announcements/:id', to: 'announcement#destroy', constraints: { subdomain: /.+/ }, via: [:delete], as: 'delete_announcement'
  match '/subjects/', to: 'subject#index', constraints: { subdomain: /.+/ }, via: [:get]
  match '/subjects/:id', to: 'subject#show', constraints: { subdomain: /.+/ }, via: [:get], as: 'subject'


  get '/pricing/', to: 'front#pricing'
  get '/users/register', to: 'login#admin_register', as: 'user_register'
  post '/users/register', to: 'login#admin_create'
  resources :admin_user, path: 'admin/admin_user'
  resources :admin_teacher, path: 'admin/admin_teacher'
  resources :admin_student, path: 'admin/admin_student'
  resources :admin_subject, path: 'admin/admin_subject'
  resources :admin_announcement, path: 'admin/admin_announcement'
  get 'admin/profile', to: 'admin_profile#show', as: 'admin_profile'
  get 'admin/profile/edit', to: 'admin_profile#edit', as: 'admin_profile_edit'
  patch 'admin/profile/edit', to: 'admin_profile#update'
  root to: 'front#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin_subject_controller.rb
class AdminSubjectController < ApplicationController
        before_action :authenticate_user!
    layout "admin_application"
    protect_from_forgery
    def index
        @subjects = Subject.where(company_id: current_user.info.company_id).paginate(:page => params[:page], :per_page => 10)
        
    end
    def show
        @subject = Subject.find_by_id(params[:id])
    end
    def new
        @subject = Subject.new
    end
    def create
        @subject = Subject.new(subject_params)
        @subject.teacher = User.find(params[:teacher_id])
        @subject.company = current_user.info.company
        if @subject.save
            redirect_to admin_subject_index_path, notice: "Subject succesfully created!" 
        else
            flash[:alert] = @subject.errors.full_messages
            render :new
        end
    end
    def edit
        @subject = Subject.find(params[:id])
    end
    def update
        @subject = Subject.find(params[:id])
        @subject.teacher = User.find(params[:teacher_id])
        if @subject.update_attributes(subject_params)
            
            @subject.students.delete_all
            students = params[:user][:user_ids]

            students.each do |student_id|
                @subject.students << User.find(student_id.to_i)
            end
            if @subject.save
                redirect_to admin_subject_path(@subject), notice: "Updated Subject."
            else
                flash[:alert] = @subject.errors.full_messages
                render :edit
            end
        else
            flash[:alert] = @subject.errors.full_messages
            render :edit
        end
    end
    def destroy
        @subject = Subject.find(params[:id])
            if @subject.destroy
                flash[:notice] = 'Subject deleted!'
                redirect_to admin_subject_index_path
                
            else
                flash[:alert] = @subject.errors.full_messages
                render :index
            end
    end

    private

    def subject_params
        params.require(:subject).permit(:title, :teacher_id, :code)
    end
end

app/helpers/admin_subject_helper.rb
module AdminSubjectHelper
end

app/views/admin_subject/edit.html.erb
<div class = "row">
  <div class="col-xs-12 col-md-8 col-md-push-2">
<div class="box box-success col-xs-12">
          <div class="box-header with-border">
            <h3 class="box-title">Update Subject</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body col-xs-12">
            <ul class="products-list product-list-in-box">
                <%= form_for @subject, url: {action: "update"} do |f| %>
                  <div class="form-group">
                      <label for="announcement_title">Title:</label>
                      <%= f.text_field :title, :class => "form-control" %>
                  </div>
                  <div class="form-group">
                    <label for="announcement_title">Subject Code:</label>
                    <%= f.text_field :code, :class => "form-control" %>
                </div>
                  <label for="announcement_title">Teacher:</label>
                  <%= select_tag 'teacher_id', options_for_select(User.includes(:info).where(infos: {is_teacher: true,company_id: current_user.info.company_id}).collect{ |u| [u.email, u.id] }),{:class => 'form-control'}%>
                  <br>
                  <label for="announcement_title">Student:</label>
                  <% User.includes(:info).where(infos: {is_admin: false, is_teacher: false,company_id: current_user.info.company_id}).each do |user| %>
                  <div class = "checkbox col-xs-12">
                    <label class = "checkbox-label">
                      <%= check_box_tag "user[user_ids][]" , user.id, f.object.students.include?(user), :class => "checkbox" %>
                      <%= user.email %>
                    </label>
                  </div>
                <% end %>
              <!-- /.item -->
            </ul>
          </div>
          <!-- /.box-body -->
          <div class="box-footer text-center">
              <%= f.submit "Update",:class => 'btn btn-sm btn-success btn-flat col-xs-12 view-more' %>
              <% end %>
          </div>
          <!-- /.box-footer -->
        </div>
      
        <!-- /.box -->
      </div>
</div>

app/views/admin_subject/index.html.erb
<div class = "row">
        <div class="col-xs-12 col-md-8 col-md-push-2">
                <%= link_to "Create", new_admin_subject_path(), :class => 'btn btn-sm btn-success btn-flat col-xs-12 col-md-3 view-more start-right'%> 
                
<div class="box box-success col-xs-12">
            <div class="box-header with-border">
              <h3 class="box-title">Subject</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body col-xs-12">
              <ul class="products-list product-list-in-box">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                            <% @subjects.each do |a|%>
                                <tr>
                                    <td><%=link_to a.get_title_code, admin_subject_path(a), :class => 'admin-link' %></td>
                                    <td>
                                        <%= link_to "Show", admin_subject_path(a), :class => 'btn btn-sm btn-primary btn-flat col-xs-12 col-md-3 view-more'%> 
                                        <%= link_to "Edit", edit_admin_subject_path(a), :class => 'btn btn-sm btn-success btn-flat col-xs-12 col-md-3 col-md-push-1 view-more'%>
                                        <%= link_to "Delete", admin_subject_path(a),  method: :delete, data: { confirm: 'Are you sure?' },  :class => 'btn btn-sm btn-danger btn-flat col-xs-12 col-md-3 col-md-push-2 view-more'%>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>

                <!-- /.item -->
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
                <div class = "col-xs-12">
                    <%= will_paginate @subjects  %>
                </div>
            </div>
            <!-- /.box-footer -->
          </div>
        
          <!-- /.box -->
        </div>

</div>

app/views/admin_subject/new.html.erb
<div class = "row">
  <div class="col-xs-12 col-md-8 col-md-push-2">
<div class="box box-success col-xs-12">
          <div class="box-header with-border">
            <h3 class="box-title">Create Subject</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body col-xs-12">
            <ul class="products-list product-list-in-box">
                <%= form_for @subject, url: {action: "create"} do |f| %>
                  <div class="form-group">
                      <label for="announcement_title">Title:</label>
                      <%= f.text_field :title, :class => "form-control" %>
                  </div>
                  <div class="form-group">
                    <label for="announcement_title">Subject Code:</label>
                    <%= f.text_field :code, :class => "form-control" %>
                </div>
                  <label for="announcement_title">Teacher:</label>
                  <%= select_tag 'teacher_id', options_for_select(User.includes(:info).where(infos: {is_teacher: true,company_id: current_user.info.company_id}).collect{ |u| [u.email, u.id] }),{:class => 'form-control'}%>
                
              <!-- /.item -->
            </ul>
          </div>
          <!-- /.box-body -->
          <div class="box-footer text-center">
              <%= f.submit "Create",:class => 'btn btn-sm btn-success btn-flat col-xs-12 view-more' %>
              <% end %>
          </div>
          <!-- /.box-footer -->
        </div>
      
        <!-- /.box -->
      </div>
</div>

app/views/admin_subject/show.html.erb
<div class = "row">
        <div class="col-xs-12 col-md-8 col-md-push-2">
<div class="box box-success col-xs-12">
            <div class="box-header with-border">
              <h3 class="box-title">Subjects</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body col-xs-12">
              <ul class="products-list product-list-in-box student-detail-show">
                   <h5>Title:</h5>
                   <h5><%= @subject.title %></h5>
                   <h5>Code:</h5>
                   <h5><%= @subject.code %></h5>
                   <h5>Teacher:</h5>
                   <% if !@subject.teacher.nil? %>
                   <h5><%=link_to @subject.teacher.email, admin_teacher_path(@subject.teacher) %></h5>
                   <% end %>
                   <h5>Student:</h5>
                    <% @subject.students.each do |s| %>
                        <h5><%= link_to s.email, admin_student_path(s) %></h5>
                    <% end %>
                <!-- /.item -->
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer text-center">
                <div class = "col-xs-12">
                <%= link_to "Edit", edit_admin_subject_path(@subject), :class => 'btn btn-sm btn-success btn-flat col-xs-12 col-md-3 col-md-push-2 view-more'%>
                <%= link_to "Delete", admin_subject_path(@subject),  method: :delete, data: { confirm: 'Are you sure?' },  :class => 'btn btn-sm btn-danger btn-flat col-xs-12 col-md-3 col-md-push-4 view-more'%>
                </div>
            </div>
            <!-- /.box-footer -->
          </div>
        
          <!-- /.box -->
        </div>

</div>